/** Lucide icon names keyed by nav item key — shared with frontend shell */
export const NAV_ICONS = {
  dashboard: 'LayoutDashboard',
  calendar: 'Calendar',
  'log-book': 'BookOpen',
  organisations: 'Building2',
  subscriptions: 'CreditCard',
  'platform-users': 'Users',
  'system-health': 'Activity',
  integrations: 'Plug',
  'support-access': 'LifeBuoy',
  'audit-logs': 'ScrollText',
  settings: 'Settings',
  sites: 'MapPin',
  zones: 'Layers',
  stations: 'DoorOpen',
  departments: 'Network',
  hosts: 'UserCheck',
  users: 'Users',
  roles: 'Shield',
  categories: 'Tags',
  workflows: 'GitBranch',
  badges: 'BadgeCheck',
  notifications: 'Bell',
  reports: 'BarChart3',
  privacy: 'Lock',
  audit: 'FileText',
  occupancy: 'Users',
  approvals: 'Clock',
  exceptions: 'AlertTriangle',
  visitors: 'Users',
  vehicles: 'Car',
  contractors: 'HardHat',
  watchlist: 'EyeOff',
  incidents: 'AlertCircle',
  overdue: 'Timer',
  'roll-call': 'Siren',
  'start-roll-call': 'Siren',
  'new-visitor': 'UserPlus',
  'new-vehicle': 'CarFront',
  expected: 'CalendarClock',
  pending: 'Hourglass',
  'check-in': 'LogIn',
  'check-out': 'LogOut',
  'visitor-logs': 'ClipboardList',
  'vehicle-logs': 'List',
  deliveries: 'Package',
  'badge-desk': 'IdCard',
  emergency: 'ShieldAlert',
  activity: 'History',
  invite: 'Send',
  'my-visitors': 'Users',
  'on-site': 'MapPinned',
  recurring: 'Repeat',
  groups: 'UsersRound',
  delegates: 'UserCog',
  profile: 'User',
  'visitor-analytics': 'TrendingUp',
  'vehicle-analytics': 'BarChart2',
  'site-comparison': 'GitCompare',
  'host-reports': 'PieChart',
  scheduled: 'Calendar',
  exports: 'Download',
  'audit-trail': 'ScrollText',
  'access-review': 'KeyRound',
  privileged: 'ShieldCheck',
  retention: 'Archive',
  register: 'BookOpen',
  evidence: 'FolderOpen',
  zones: 'Map',
  zones_emergency: 'Map',
  unresolved: 'UserX',
  contacts: 'Phone',
  previous: 'History',
  export: 'Printer',
};

export const PORTAL_ICONS = {
  platform: 'Globe',
  admin: 'Settings2',
  security: 'Shield',
  station: 'ConciergeBell',
  host: 'Briefcase',
  management: 'LineChart',
  compliance: 'Scale',
  emergency: 'Siren',
};

export function resolveNavIcon(key) {
  return NAV_ICONS[key] || 'Circle';
}
